kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: lab-cluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30080
    hostPort: 30080
  - containerPort: 30443
    hostPort: 30443
  - containerPort: 30090
    hostPort: 30090
  - containerPort: 30030
    hostPort: 30030
  - containerPort: 30686
    hostPort: 30686
- role: worker
