name: GitOps Pipeline

on:
  push:
    branches: [ main ]
    paths: [ 'lab_scripts/sample-app/**' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: sample-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # push 권한 추가
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=latest
          type=sha,prefix={{branch}}-,format=short

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: lab_scripts/sample-app
        file: lab_scripts/sample-app/docker/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Update Kubernetes manifests
      run: |
        # metadata action에서 생성된 짧은 SHA 태그 사용
        IMAGE_TAG=$(echo "${{ steps.meta.outputs.tags }}" | grep "main-" | head -1)
        echo "Updating image to: ${IMAGE_TAG}"
        
        # app.yaml 업데이트 (정확한 패턴 매칭)
        sed -i "s|image: ghcr.io/[^/]*/[^/]*/sample-app:.*|image: ${IMAGE_TAG}|g" lab_scripts/sample-app/k8s/app.yaml
        
        # 변경사항 확인
        grep "image:" lab_scripts/sample-app/k8s/app.yaml
        
        # 변경사항 커밋
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add lab_scripts/sample-app/k8s/app.yaml
        git commit -m "Update image to ${IMAGE_TAG}" || exit 0
        git push origin main